### ISSUE TITLE
frequency-dependent rates

### ISSUE THREAD

**Issue by sdwfrost** [CompEvol/MASTER#25]
@tgvaughan , nice job on MASTER, it could potentially save me a lot of time. This is more of a feature query/request; in many epidemiological models, infection is of the form b_S_I/N where N is the total population size, rather than b_S_I. Is there a way to implement this in the current build, or if not, could this be added?

**Comment by tgvaughan** [comment]
Could incorporate this into the rate multiplier!

**Comment by ekankaka** [comment]
Hi Tim.
Thanks for MASTER. 
I want to create a  population-dependent rate. Specifically, the antigen-driven T-Cell proliferation rate in model (14) of [this paper](https://www.sciencedirect.com/science/article/pii/S0022519312006170) varies with amount of Virus (V) - which is included in the numerator and denominator. 
I created the function below, and then used it in a rate multiplier, but keeps throwing the error: "**validate and intialize error: Variable V in predicate expression was not found in reaction string.** "   _I got the same error even when i made unifected T cells, infected T cells, and Virus demes of the same population (T[0] and T[1], and T[2] respectively)_. **How can solve this in MASTER?**

        
        <function spec='Function' id='freqDepRateMultiplier' params="x">
          { (0.01 * x) / (300 + x) }
        </function>

        
         <reaction spec='Reaction' rate="1">
            <rateMultiplier spec="RateMultiplier" value="freqDepRateMultiplier(V)"/>
            T + V -> 2T + V
         </reaction>

**Comment by tgvaughan** [comment]
Hi @ekankaka, glad you're finding it useful.

Sadly this still isn't possible to do in MASTER - rates are assumed to be constant w.r.t. population sizes.  (That is, the overall master equation is still assumed to be of the form described in equation 1 of the [documentation](https://github.com/tgvaughan/MASTER/wiki))  The comment I made above was just to note down the possibility of extending the functionality of the rate multipliers to handle this, but the extension hasn't been implemented.

The reason you're seeing the error you're seeing is that MASTER is specifically looking for population index variables (such as i in T[i]) in your reaction string.  It doesn't consider V a variable (it's a population type).
