### ISSUE TITLE
Sample lineages from different populations

### ISSUE THREAD

**Issue by sdwfrost** [CompEvol/MASTER#32]
Dear @tgvaughan 

This is more of a feature request, and hence can be overlooked! I've been looking at structured populations, and I'd like to sample specific numbers of lineages from different populations. I can do this by reading in the full tree, then sampling from that, but my R code to process MASTER trees is very slow (listed below, FYI)

Is it possible to extend LineageSampler to give conditions for the lineages of different populations?

A related issue would be to give conditions such that the number of lineages always exceeds the requested number of lineages. Is there a way to do this?

```
process.master <- function(nexfilename){
  nexfile <- scan(nexfilename,what=list(character()),quiet=TRUE)
  # find which lines contain "tree " using grepl
  #treeidx <- unlist(lapply(nexfile[[1]],grepl,pattern="tree "))
  treeidx <- (nexfile[[1]])=="tree"
  nlines <- length(treeidx)
  treelabels <- as.integer(unlist(lapply(strsplit(nexfile[[1]][seq(1,nlines)[treeidx]+1],"_"),"[",2)))+1
  # count the number of trees
  numtrees <- sum(treeidx)
  # calculate start and end lines for each tree
  start <- seq(1,nlines)[treeidx]
  end <- c(start[2:length(start)]-1,nlines-1)
  treelist <- list()
  for(i in 1:numtrees){
    enwk <- nexfile[[1]][start[i]:end[i]][4]
    # delete reactions and times
    nwk <- gsub(",reaction(.*?)\\]","",enwk)
    # delete isolated times
    nwk <- gsub(",time(.*?)\\]","",nwk)
    # get rid of type info
    nwk <- gsub("\\[&type=\"","",nwk)
    # get rid of quotes and newlines
    nwk <- gsub("\"","",nwk)
    nwk <- gsub("\n","",nwk)
    tree <- read.newick(text=nwk)
    if(length(tree$tip.label)>1){
    tree <- collapse.singles(tree)
    }else{
      tree <- NA
    }
    treelist[[treelabels[i]]] <- tree
  }
  treelist
}
```

**Comment by ekankaka** [comment]
Hi @tgvaughan , is it possible to sample a transmission tree at multiple timepoints using the inheritance post processor, e.g. if i want to sample 10 leaves at sampling times 10 and 20 each, and produce a tree with the sampled leaves and their ancestors?

        <inheritancePostProcessor spec='LineageSampler'
                                  nSamples="10"
                                  **samplingTime="10,20"**
                                  reverseTime="false"
                                  noClean="false"/>

**Comment by tgvaughan** [comment]
Hi @ekankaka, as I mentioned in the issue you raised, I'd try remaster for this instead.  The documentation is [here](https://tgvaughan.github.io/remaster).
