### ISSUE TITLE
URL invalid

### ISSUE THREAD

**Issue by richelbilderbeek** [CompEvol/MASTER#38]
The project its description and its README.me point to `http://compevol.github.io/MASTER`, which is an unknown URL.

**Comment by tgvaughan** [comment]
Thanks, Richel.  I don't know what the problem here is yet - I'll get back
to you when I know more.

**Comment by tgvaughan** [comment]
Well that was a strange glitch, and it affected all of our compevol project pages.  Pushing up commits to the repos for each of those projects seems to have fixed the problem.  Thanks again!
