### ISSUE TITLE
Who infected whom

### ISSUE THREAD

**Issue by thednainus** [CompEvol/MASTER#52]
I have started using MASTER, but I would like to know whether it is possible to get a list of who transmitted to whom using the InheritanceTrajectory?

Thanks,
Fabricia.

**Comment by tgvaughan** [comment]
Dear Fabricia,

No, this isn't directly possible.  But if you generate the full tree, you could recover this information from it.  (This would require some post-processing using R/Python/..).

Hope this helps,
Tim
