### ISSUE TITLE
master not in available in BEAST v2.7 packages

### ISSUE THREAD

**Issue by ekankaka** [CompEvol/MASTER#53]
Hi Tim,
These instructions do not work, particularly installing MASTER from within Beauti. 
Instructions on the[ MASTER web page](http://tgvaughan.github.io/MASTER/): 
"MASTER is a [BEAST 2](http://www.beast2.org/) package and can therefore be installed easily from within BEAUti. Simply download and install the latest version of BEAST 2 from the [web site](http://www.beast2.org/), open BEAUti, then choose "File->Manage Packages" and select MASTER from the package list that appears. MASTER simulations can then be run by simply running BEAST and selecting the MASTER-specific XML input file. "

**Comment by tgvaughan** [comment]
Hi @ekankaka, BEAST 2 version 7.0 introduced major changes, and I haven't yet had time to update MASTER to bring it in line with these.  I will get to this eventually, but in the meantime you can continue to use MASTER with BEAST 2 version 6.x.

**Comment by tgvaughan** [comment]
Your comment spurred me into action. :)  I've released a new MASTER version (7.0.0) which is compatible with BEAST 2.7.
