### ISSUE TITLE
Multiple sampling of transmission tree

### ISSUE THREAD

**Issue by ekankaka** [CompEvol/MASTER#54]
Hi @tgvaughan , is it possible to sample a transmission tree at multiple timepoints using the inheritance post processor, e.g. if i want to sample 10 leaves at sampling time 10 and 10 leaves at sampling time 20; and then produce a tree with all sampled leaves and their ancestors?

        <inheritancePostProcessor spec='LineageSampler'
                                  nSamples="10"
                                  **samplingTime="10,20"**
                                  reverseTime="true"
                                  noClean="false"/>

**Comment by tgvaughan** [comment]
Hi @ekankaka, it's possible to set something like this (using noClean="true" and then subsequently pruning marked lineages) but it's very awkward.  If you're interested in this, I'd instead give [remaster](https://github.com/tgvaughan/remaster) a go, as it's much more capable with respect to this kind of thing.
